name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Hoặc master nếu bạn dùng nhánh master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Bước 1: Checkout mã nguồn từ repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Bước 2: Cài đặt Node.js để sử dụng Sass
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Phiên bản Node.js

      # Bước 3: Cài đặt Sass
      - name: Install Sass
        run: npm install -g sass

      # Bước 4: Biên dịch SCSS thành CSS
      - name: Build SCSS
        run: sass scss/style.scss assets/style.css # Đường dẫn SCSS và CSS

      # Bước 5: Triển khai lên GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # Thư mục chứa file HTML, CSS, JS
